version: "3"

services:
  geokey:
    build:
      context: .
    links:
      - db
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s
    command: tail -f /dev/null
    ports:
      - "9000:8000"
    environment:
      DJANGO_DATABASE_HOST: db
      SOCIAL_AUTH_GITHUB_KEY: ${SOCIAL_AUTH_GITHUB_KEY}
      SOCIAL_AUTH_GITHUB_SECRET: ${SOCIAL_AUTH_GITHUB_SECRET}
    volumes:
      - ./geokey:/app/geokey
  db:
    build: db
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django123
      POSTGRES_DB: geokey
