# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-24 15:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggerhistory',
            name='comment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='historical',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='location_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='observation_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='subset_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='usergroup_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loggerhistory',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loggerhistory',
            name='project_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loggerhistory',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
