# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggerhistory',
            old_name='location',
            new_name='field',
        ),
        migrations.RenameField(
            model_name='loggerhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
