# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-02 20:00
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_loggerhistory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggerhistory',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='loggerhistory',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
