# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-14 11:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_id', models.CharField(max_length=1000, null=True)),
                ('category_id', models.CharField(max_length=1000, null=True)),
                ('user_id', models.CharField(max_length=1000, null=True)),
                ('action', models.CharField(max_length=300)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(geography=True, null=True, srid=4326)),
                ('action_id', models.CharField(choices=[(b'created', b'created'), (b'deleted', b'deleted'), (b'updated', b'updated')], default=b'created', max_length=20)),
            ],
        ),
    ]
