# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('socialinteractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_socialinteractions', to='socialaccount.SocialAccount')),
            ],
            options={
                'ordering': ['socialinteraction__name'],
            },
        ),
        migrations.RemoveField(
            model_name='socialinteraction',
            name='socialaccount',
        ),
        migrations.AddField(
            model_name='socialaccounts',
            name='socialinteraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialaccount_of', to='socialinteractions.SocialInteraction'),
        ),
        migrations.AddField(
            model_name='socialinteraction',
            name='socialaccounts',
            field=models.ManyToManyField(related_name='socialinteractions', through='socialinteractions.SocialAccounts', to='socialaccount.SocialAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccounts',
            unique_together=set([('socialinteraction', 'socialaccount')]),
        ),
    ]
