# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialinteractions', '0003_auto_20171024_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialinteraction',
            name='link',
            field=models.TextField(blank=True, default=b'https://communitymaps.org.uk/project/$project_id$/contribution/$contribution_id$', null=True),
        ),
        migrations.AlterField(
            model_name='socialinteraction',
            name='text_to_post',
            field=models.TextField(blank=True, default=b'New contribution added to $project$. Check it out here $link$', null=True),
        ),
    ]
